version: '3'
services:
  web:
    build: ./web
    depends_on:
      - crossbar
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
    environment:
      FLASK_ENV: development
  crossbar:
    image: "crossbario/crossbar"
    ports:
      - "8080:8080"